import { CheckItem } from "@/features/ui/Checkitem";
import { Headline } from "@/features/ui/Headline";

export default function Page() {
   return (
      <div className="text-gray-800">
         <Headline>About us</Headline>

         <p className="mb-4 mt-4">
            At <strong>Spain Properties</strong>, we believe that finding your dream home in Spain should be exciting,
            effortless, and inspiring. While we are a fictional agency created for a private web project, our mission is
            real: to showcase the beauty, charm, and lifestyle of Spanish real estate through a clean, modern online
            experience.
         </p>

         <img src="images/team.png" alt="spainproperties" className="w-full h-80 object-cover rounded-xl grayscale-25" />

         <p className="mb-4">
            Our "agency" specializes in a handpicked selection of properties—from sunny coastal villas and charming
            countryside homes to sleek modern apartments in the heart of Spanish cities. Whether you're imagining a
            peaceful retirement near the sea or a bold investment in a growing urban hub, <strong>Spain Properties</strong>{' '}
            is here to help bring that vision to life—virtually.
         </p>

         <p className="mb-4">
            Though our listings aren't real, the care we’ve put into crafting this digital space reflects our passion for
            design, storytelling, and the Mediterranean way of life.
         </p>

         <h2 className="text-2xl font-semibold mt-8 mb-3">Why Spain?</h2>
         <p className="mb-4">
            Spain offers more than just sunshine and sangria. With its rich culture, diverse landscapes, welcoming
            communities, and high quality of life, it continues to be one of the top destinations for property seekers
            around the world.
         </p>

         <h2 className="text-2xl font-semibold mt-8 mb-3">A Digital Showcase</h2>
         <ul className="list-disc list-inside space-y-2">
            <CheckItem>How real estate can be presented in a visually engaging way</CheckItem>
            <CheckItem>The user experience of browsing properties</CheckItem>
            <CheckItem>Web technologies and design systems used in modern applications</CheckItem>
            <CheckItem>All data generated via faker dependency </CheckItem>
            <CheckItem>Images from pexels or generated by AI </CheckItem>
         </ul>

         <p className="mt-6 mb-6 text-sm text-gray-500">
            This page is part of a fictional project. No actual properties are for sale.
         </p>
      </div>
   );
}