module.exports = {
  numberOfAgents: 6,
  numberOfProperties: 5000,
  numberOfBedrooms: { min: 1, max: 4 },
  numberOfBathrooms: { min: 1, max: 2 },
  plotSize: { min: 100, max: 1500 },
  buildSize: { min: 40, max: 350 },
  buildYear: { min: 2000, max: 2023 },
  parkingSlots: { min: 0, max: 3 },
  priceRange: { min: 50000, max: 800000, multipleOf: 1000 },

  cities: [
    "Alicante",
    "Benidorm",
    "Torrevieja",
    "Denia",
    "Jávea",
    "Calpe",
    "Altea",
    "Villajoyosa",
    "Santa Pola",
    "Elche",
    "Moraira",
    "Guardamar del Segura",
    "Albir",
    "Benissa",
    "Teulada",
    "Orihuela Costa",
    "La Nucia",
    "Pego",
    "Rojales",
    "San Fulgencio",
  ],
  features: [
    "Air conditioning",
    "Swimming pool",
    "Garden",
    "Terrace",
    "Garage",
    "Sea view",
    "Mountain view",
    "Furnished",
    "Equipped kitchen",
    "Storage room",
    "Lift",
    "Fireplace",
    "Barbecue area",
    "Playground",
    "Gym",
    "Sauna",
    "Jacuzzi",
    "Smart home system",
    "Security system",
    "Solar panels",
    "Home automation",
    "Double glazing",
    "Central heating",
    "Internet",
    "Satellite TV",
    "Community pool",
    "Tennis court",
    "Basketball court",
    "Golf course",
    "Beach access",
    "Parks",
  ],
};
